# Quiet Light theme for kitty
# Ported from the VS Code Quiet Light theme
#
# Installation instructions:
#
#  cp quiet-light.conf ~/.config/kitty/
#  echo "include quiet-light.conf" >> ~/.config/kitty/kitty.conf
#
# Then reload kitty for the config to take effect.
# Alternatively copy paste below directly into kitty.conf

foreground            #333333
background            #F5F5F5
selection_foreground  #333333
selection_background  #C9D0D9

url_color #4B69C6

# black
color0  #000000
color8  #666666

# red
color1  #AA3731
color9  #CD3131

# green
color2  #448C27
color10 #12CE14

# yellow
color3  #9C5D27
color11 #B5BA01

# blue
color4  #4B69C6
color12 #6F8FDB

# magenta
color5  #7A3E9D
color13 #D94CD9

# cyan
color6  #0798BC
color14 #7AB9CC

# white
color7  #AAAAAA
color15 #F5F5F5

# Cursor colors
cursor            #54494B
cursor_text_color #F5F5F5

# Tab bar colors
active_tab_foreground   #F5F5F5
active_tab_background   #705697
inactive_tab_foreground #333333
inactive_tab_background #E0E0E0

# Marks
mark1_foreground #F5F5F5
mark1_background #AA3731

# Splits/Windows
active_border_color #705697
inactive_border_color #AAAAAA
