" Packages
packadd! dracula

" Config
set nocompatible
filetype plugin indent on
syntax on
set hidden

set number
set relativenumber

set wrap
set textwidth=120

set title

set backspace=indent,eol,start

set scrolloff=3
set laststatus=2

set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set copyindent
set expandtab
set noshiftround

set hlsearch
set incsearch
set showmatch
set smartcase

set showmode
set showcmd

" Movement
nnoremap j gj
nnoremap k gk

" Leader
nnoremap <Space> <nop>
let mapleader=" "

" Colors
set termguicolors
set background=dark
colorscheme dracula
"" Disable Background Color Erase
set t_ut=
